name: build and test workflow
on: 
  push:
    branches:
      - main
  pull_request:
      branches:
      - main
jobs:
  build-debug:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: build code
        run: dotnet build DuckHappiness/DuckHappiness.csproj --configuration Debug
        
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: build code
        run: dotnet build DuckHappiness/DuckHappiness.csproj --configuration Release
        
  test-debug:
    needs: build-debug
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: run tests
        run: dotnet test TestPetDuck/TestPetDuck.csproj

  analyze:
    needs: build-debug
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: analyze code
        run: dotnet tool install -g dotnet-format && dotnet format DuckHappiness/DuckHappiness.csproj

        
  test-release:
    needs: build-release
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: run tests
        run: dotnet test TestPetDuck/TestPetDuck.csproj

